#pragma once

enum class LevelNumbers : uint64_t {
    Default = 100000,
    Mansion = 0,
    Train = 1,
    Carry = 2,
    Mountain = 3,
    Demolition = 4,
    Castle = 5,
    Water = 6,
    PowerPlant = 7,
    Aztec = 8,
    Dark = 9,
    Steam = 10,
    Ice = 11,
    Thermal = 12,
    Factory = 13,
    Golf = 14,
    City = 15,
    Forest = 16,
    Laboratory = 17,
    Lumber = 18,
    RedRock = 19,
    Tower = 20,
    Miniature = 21,
    CopperWorld = 22,
    Port = 23,
    Underwater = 24,
    Dockyard = 25,
    Museum = 26,
    Hike = 27
};